### ISSUE TITLE
CANT OPEN SETTINGS

### ISSUE THREAD

**Issue by BOMPTONTV** [zaldor30/GuildRecruiter#79]
Hello, Everytime i open GuildRecruiter and attempt to open settings I get a LUA Error. I can't even open settings to make any kind of custom messages.

**Comment by zaldor30** [comment]
Make sure you are running 2.2.53.  You can also access the settings from
the options screen.  I am working on a new version to fix the many small
issues that was created by War Within.

**Comment by zaldor30** [comment]
Should be working.
